version: 1.2.{build}
image: Visual Studio 2019
configuration: Release
platform: Any CPU

pull_requests:
  do_not_increment_build_number: true
nuget:
  disable_publish_on_pr: true
before_build:
- cmd: nuget restore .\src\

build:
  verbosity: normal